# Generated by Django 4.0.5 on 2022-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='address',
            name='unique_user_address',
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'country', 'state', 'city', 'address_1', 'address_2'), name='unique_user_address'),
        ),
    ]
